application: thom-nichols
version: b
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: django
  version: "1.2"
- name: webob
  version: "1.1.1"
- name: pycrypto
  version: 'latest'

handlers:
- url: /static
  static_dir: static

- url: /images
  static_dir: static/images

- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots.txt

#- url: /admin/shell.*
#  script: handlers/shell/shell.py
#  login: admin

- url: .*
  script: main.application

skip_files: |
 ^(.*/)?(
 (app\.yaml)|
 (app\.yml)|
 (index\.yaml)|
 (index\.yml)|
 (#.*#)|
 (.*~)|
 (.*\.py[co])|
 (.*/RCS/.*)|
 (\..*)|
 (dev/.*)|
 (tests/.*)|
 (docs/.*)|
 (static/hosted/.*)|
 (.*\.markdown)|(.*\.md)|
 (license\.txt)|
 (setup\.py)|
 (README.*)|
 (Thumbs\.db)
 )$
